[package]
name = "aoc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.89", features = ["full"] }

[dev-dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
